name: native_gallery_app
description: Isang purong native na gallery app para sa Android.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Ito ang official at updated native plugin para sa pagbasa ng storage gallery
  photo_manager: ^3.0.0 

flutter:
  uses-material-design: true