name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # Ini-update sa Node 24 para tugma sa GitHub runner

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17' # Ini-update sa JDK 17 para hindi mag-error ang sdkmanager

    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova Project
      run: |
        cordova create MyCastApp com.example.mycastapp MyCastApp
        cd MyCastApp
        cordova platform add android
        
        # Burahin ang default files ng Cordova at ipalit ang code mo mula sa Acode
        rm -rf www/*
        cp -r ../index.html www/
        cp -r ../peerjs.min.js www/

    - name: Build Android APK
      run: |
        cd MyCastApp
        cordova build android --release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-cast-app-apk
        path: MyCastApp/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
